# Generated by Django 5.1 on 2024-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Укажите фамилию сотрудника', max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Укажите имя сотрудника', max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, help_text='Укажите отчество сотрудника', max_length=30, null=True, verbose_name='Отчество')),
                ('position', models.CharField(help_text='Укажите должность сотрудника.', max_length=100, verbose_name='Должность')),
                ('department', models.CharField(blank=True, help_text='Укажите отдел сотрудника.', max_length=100, null=True, verbose_name='Отдел')),
                ('hired_date', models.DateField(blank=True, help_text='Укажите дату приема на работу.', null=True, verbose_name='Дата приема на работу')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование задачи.', max_length=200, verbose_name='Наименование задачи')),
                ('description', models.TextField(blank=True, help_text='Введите описание задачи.', null=True, verbose_name='Описание задачи')),
                ('due_date', models.DateField(help_text='Укажите срок выполнения задачи.', verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('on_hold', 'На паузе'), ('canceled', 'Отменена'), ('overdue', 'Просрочена')], default='new', help_text='Выберите статус задачи.', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', help_text='Укажите приоритет задачи.', max_length=10, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
