# Generated by Django 5.1 on 2024-08-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(help_text='Укажите пользователя, связанного с сотрудником.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Укажите сотрудника, ответственного за выполнение задачи.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_tracker.employee', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Выберите родительскую задачу, если задача является зависимой.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='task_tracker.task', verbose_name='Родительская задача'),
        ),
    ]
