# Generated by Django 5.1 on 2024-08-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
