# Generated by Django 5.1 on 2024-08-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_remove_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
